Add support for submitting reviews
mensatt/frontend-old pull request #113
Opened 2022-07-25 13:42 UTC by GamerBene19

Same as #112 but hopefully netlify works this time ^^

2022-07-25 13:51 UTC, stormofice approved these changes
Looks good to me!

2022-07-25 13:51 UTC, stormofice commented on src/components/occurrence/review-modal/ReviewModal.tsx
> +        }
Can we also check for correct file extensions (png, jpg, ...)?
Proper validation is done in the backend, but this prevents someone from simply uploading "random" files easily

2022-07-25 13:59 UTC, GamerBene19 commented on src/components/occurrence/review-modal/ReviewModal.tsx
> +        }
We could, but I don't think it's worth it here. A PNG-image stays a PNG image even if I change it's extension to `.foobar`. AFAIK the backend does not care about the file-extension so I don't see a reason why we should check for a proper extension here.

2022-07-25 14:08 UTC, stormofice commented on src/components/occurrence/review-modal/ReviewModal.tsx
> +        }
It stops someone messing around with the backend by spamming it with non image files which will be discarded anyway.
Obviously the file extension does not specify the actual file type, but it's a simple detection and wouldn't hurt imo.

2022-07-25 14:17 UTC, GamerBene19 commented on src/components/occurrence/review-modal/ReviewModal.tsx
> +        }
> It stops someone messing around with the backend by spamming it with non image files which will be discarded anyway.

If your concern is protecting the backend (which it seems to be) than I don't think this check is necessary here. A malicious actor could (and likely would) be using the GQL-Mutation (where you don't have that limitation) directly instead of our frontend.

2022-07-25 14:20 UTC, stormofice commented on src/components/occurrence/review-modal/ReviewModal.tsx
> +        }
I still disagree, as I can imagine someone probing around the frontend and trying to upload bogus files "for fun".
Preventing it is very simple, so I don't see why we shouldn't implement it.

2022-07-25 14:27 UTC, tobiges commented on src/components/occurrence/review-modal/ReviewModal.tsx
> +        }
I have to agree with @stormofice, it can be quite painful uploading a new image on a slow connection only to find out that you accidentally uploaded a wrong file or your image has an unsupported format. It won't catch all of these cases but, but the majority.

2022-07-25 14:30 UTC, GamerBene19 commented on src/components/occurrence/review-modal/ReviewModal.tsx
> +        }
Alright. It looks like I've been outvoted. I'll quickly implement such a feature.

2022-07-25 15:27 UTC, GamerBene19 commented on src/components/occurrence/review-modal/ReviewModal.tsx
> +        }
Done @tobiges @stormofice

2022-07-25 15:33 UTC, stormofice requested changes
Choosing a file with an invalid extension and then selecting another one with a valid extension does not remove the error message (and disable rating):
![grafik](https://user-images.githubusercontent.com/58337328/180817428-66027c32-1acd-48a1-a711-3ddca1b2dc2a.png)

There should also be a way to fully unselect a previously uploaded image, if you decide not to include an image with your rating.

2022-07-25 15:43 UTC, GamerBene19 commented
> Choosing a file with an invalid extension and then selecting another one with a valid extension does not remove the error message

Good catch. Should be fixed

2022-07-26 13:19 UTC, stormofice requested changes
I really like the changes, but I still encounter some images:
- Images disappear on some zoom levels

https://user-images.githubusercontent.com/58337328/181014830-9c5b5810-dee0-412f-aa8b-8dd05d1f201b.mp4

- Switching from an invalid to a valid file extension does not make the error message go away

https://user-images.githubusercontent.com/58337328/181015357-f26e1cae-1335-47fe-b74a-40a77884c175.mp4

2022-07-26 13:43 UTC, GamerBene19 commented
> Switched from an invalid to a valid file extension does not make the error message go away

Should be fixed now for real

2022-07-26 19:11 UTC, stormofice approved these changes
Looks good now, approved!

(Images not being shown is out of scope for this PR)

2022-07-26 19:12 UTC, merged