Show dishes in admin panel
mensatt/frontend-old pull request #117
Opened 2022-07-26 15:02 UTC by stormofice

This PR integratesa simple table view of all existing dishes into the admin panel.
Pagination and the ability to edit dish names should be implemented in the features.
There are some queries and mutations missing to also display the aliases' properties.

2022-07-26 20:26 UTC, GamerBene19 requested changes
Thanks for your contribution - changes look good so far, however there are a few things I'd change/like to discuss. See comments below

2022-07-26 20:26 UTC, GamerBene19 commented on src/assets/icons/logout.svg
> +</svg>
I'm not necessarily against it - but what lead you to change this svg?
If it was intentional - could you make that change be its own commit?

2022-07-26 20:26 UTC, GamerBene19 commented on src/pages/admin/dishes.tsx
> +    return data.dishes.map((elem) => ({
I'm often guilty of this myself, but I'd be nicer (especially once components grow) to not use `elem` in `map` (and `filter`, `sort`, ...) but to properly name what is mapped over. In this case I'd use `dish`.

2022-07-26 20:26 UTC, GamerBene19 commented on src/pages/admin/dishes.tsx
> +    { fieldName: 'nameEn', displayName: 'English name' },
While it might work for now I think having a separate column for each language scales badly. Any ideas how to do this better (in the future)?

2022-07-26 20:26 UTC, GamerBene19 commented on src/pages/admin/dishes.tsx
> +      aliases: elem.aliases.join(','),
I don't think this is `join(,)` approach is good enough. It currently only works because each dish has one alias.
I think there needs to be a better solution here.

Perhaps a button that opens a Popup that displays a table of all aliases for that dish is a better idea here?

2022-07-26 20:26 UTC, GamerBene19 commented on src/pages/admin/dishes.tsx
> +      nameDe: elem.nameDe ?? '<NULL>',
Currently `nameDe` cannot be null/undefined so `?? '<NULL>'` is useless here.

2022-07-26 20:27 UTC, stormofice commented on src/assets/icons/logout.svg
> +</svg>
Commited this by accident, some kind of auto-formatting got ahold of the file, will undo.

2022-07-26 20:27 UTC, stormofice commented on src/pages/admin/dishes.tsx
> +    return data.dishes.map((elem) => ({
Good catch, I have already renamed it locally!

2022-07-26 20:28 UTC, stormofice commented on src/pages/admin/dishes.tsx
> +      nameDe: elem.nameDe ?? '<NULL>',
You are right, I'll remove it.

2022-07-26 20:29 UTC, stormofice commented on src/pages/admin/dishes.tsx
> +    { fieldName: 'nameEn', displayName: 'English name' },
I don't see us supporting more languages even in the far future, as the underyling api only supplies german and english values. I don't think we will manually translate every dish any time soon 😅

2022-07-26 20:33 UTC, GamerBene19 commented on src/pages/admin/dishes.tsx
> +    { fieldName: 'nameEn', displayName: 'English name' },
Fair point.

2022-07-27 17:32 UTC, stormofice commented on src/pages/admin/dishes.tsx
> +      aliases: elem.aliases.join(','),
I think it will do for now, but needs to be revisited later on when we have a proper popup component.

2022-07-27 18:01 UTC, tobiges requested changes, later dismissed
popup instead of inline editing

2022-07-27 18:23 UTC, GamerBene19 requested changes
Thanks for the great changes!

There are a few things I'd do differently however. See comments for details.

One additional thing I've noticed: If you change a name, the value from the `aliases` column does not change. Is this intentional?
![image](https://user-images.githubusercontent.com/20821976/181344751-ec61981c-3802-42c5-b839-d8f89084abf8.png)

2022-07-27 18:23 UTC, GamerBene19 commented on src/assets/icons/logout.svg
> +</svg>
> will undo.

@stormofice this has never happened, has it?

2022-07-27 18:23 UTC, GamerBene19 commented on src/components/admin/DishInput.module.scss
> +}
I think this should be set where the component is used (dish page), not where it's defined.

2022-07-27 18:23 UTC, GamerBene19 commented on src/components/admin/DishInput.tsx
> +const DishInput = ({
I think `DishNameInput` is a more fitting name here.

2022-07-27 18:23 UTC, GamerBene19 commented on src/components/admin/DishInput.tsx
> +}) => {
I think typing this like so is more robust:
(If `id` is not needed you could also exclude that too.)
```suggestion
type Dish = GetAdminPanelDishesQuery['dishes'][number];

const DishInput = ({
  dish,
  valueAttribute,
}: {
  dish: Dish;
  valueAttribute: Exclude<keyof Dish, '__typename' | 'aliases'>;
}) => {
```

2022-07-27 18:23 UTC, GamerBene19 commented on src/components/admin/DishInput.tsx
> +          nameDe: valueAttribute == 'nameDe' ? e.target.value : dish.nameDe,
Please use `===` instead of `==` here and everywhere else. I'll add a linting rule for this shortly.

2022-07-27 18:23 UTC, GamerBene19 commented on src/components/admin/DishInput.tsx
> +type ValueType = 'id' | 'nameDe' | 'nameEn';
Why do you need `id` here?

2022-07-27 18:23 UTC, GamerBene19 commented on src/components/admin/DishInput.tsx
> +const DishInput = ({
I'd be nice if this component could become a general component for Editing string values in the admin panel. But I think it's out of scope for this PR

2022-07-27 18:23 UTC, GamerBene19 commented on src/pages/admin/dishes.tsx
> +      aliases: elem.aliases.join(','),
> when we have a proper popup component.

We do have a proper Popup component.

2022-07-27 18:45 UTC, stormofice commented on src/components/admin/DishInput.tsx
> +}) => {
Sounds good, will do!

2022-07-27 18:45 UTC, stormofice commented on src/components/admin/DishInput.tsx
> +          nameDe: valueAttribute == 'nameDe' ? e.target.value : dish.nameDe,
Sure.

2022-07-27 18:46 UTC, stormofice commented on src/components/admin/DishInput.tsx
> +type ValueType = 'id' | 'nameDe' | 'nameEn';
I swapped to your propsed solution above.

2022-07-27 18:47 UTC, stormofice commented on src/components/admin/DishInput.tsx
> +const DishInput = ({
I did notice that, but I was not sure how to do it correctly.
Should I create an issue, so this doesn't get lost?

2022-07-27 18:47 UTC, stormofice commented on src/components/admin/DishInput.tsx
> +const DishInput = ({
Agreed.

2022-07-27 18:51 UTC, stormofice commented on src/components/admin/DishInput.module.scss
> +}
Why do it like this for this component, but not for the other components (like the footer or occurrence)?
I would have thought that a component should be self contained, so there is no need to configure or style it from the outside.

2022-07-27 18:53 UTC, stormofice commented
> One additional thing I've noticed: If you change a name, the value from the aliases column does not change. Is this intentional?
It is intentional as dish aliases need to be supported properly later on, but this would be out of scope for this pr.

2022-07-27 18:55 UTC, stormofice commented on src/assets/icons/logout.svg
> +</svg>
Oopsie daisy.

2022-07-27 18:59 UTC, GamerBene19 commented on src/components/admin/DishInput.tsx
> +const DishInput = ({
I'll add it to #108.

2022-07-28 08:34 UTC, GamerBene19 commented on src/components/admin/DishInput.module.scss
> +}
I think you misunderstand sth. here. Basically you only want to style the "inside" of a component.
In this case that means not specifying the width where the component is defined, but rather where it's used.

Example: Say I'd want to additionally use that input somewhere else where I want a button next to it. I't like the input to be 50% wide there while it still should stay 95% wide where you use it.

When you add styling at the definition is not possible

2022-07-28 08:35 UTC, GamerBene19 commented
> > One additional thing I've noticed: If you change a name, the value from the aliases column does not change. Is this intentional?
> 
> It is intentional as dish aliases need to be supported properly later on, but this would be out of scope for this PR.

I see, was just sth that caught my attention.

2022-07-28 15:19 UTC, stormofice commented on src/components/admin/DishInput.module.scss
> +}
Should be fixed.

2022-07-28 15:19 UTC, stormofice commented on src/assets/icons/logout.svg
> +</svg>
Should be resolved now.

2022-07-28 15:21 UTC, stormofice commented on src/pages/admin/dishes.tsx
> +      aliases: elem.aliases.join(','),
This is implemented in the newest version.

2022-07-28 16:31 UTC, GamerBene19 requested changes
Liking the changes!

Just a few more things

2022-07-28 16:31 UTC, GamerBene19 commented on src/components/admin/DishInput.tsx
> +const DishInput = ({
You haven't changed the name yet, have you?

2022-07-28 16:31 UTC, GamerBene19 commented on src/pages/admin/dishes.module.scss
> +.main {
I'm not 100% sure if this works but could you move this file and `dishes.tsx` to a `dishes` subdirectory?

2022-07-28 16:31 UTC, GamerBene19 commented on src/pages/admin/dishes.tsx
> +          dish.aliases.length == 1 ? (
`===` please

2022-07-28 16:31 UTC, GamerBene19 commented on src/pages/admin/dishes.tsx
> +      },
While this does work, imo this is cleaner:
```suggestion
      aliases:
        dish.aliases.length == 1
          ? dish.aliases[0]
          : {
              node: (
                <Popup
                  trigger={<button className="button">View all aliases</button>}
                >
                  {dish.aliases.map((x) => (
                    <>
                      <p className={styles.popupText} key={x}>
                        {x}
                      </p>
                      <hr className={styles.popupDivider} />
                    </>
                  ))}
                </Popup>
              ),
              value: dish.aliases.at(0) ?? '<NULL>',
            },
```

2022-07-28 16:31 UTC, GamerBene19 commented on src/pages/admin/dishes.tsx
> +        value: dish.aliases.at(0) ?? '<NULL>',
Why are you not using `dish.aliases[0]` here?

2022-07-28 16:31 UTC, GamerBene19 commented on src/pages/admin/dishes.tsx
> +              {dish.aliases.map((x) => (
`x` => `alias`

2022-07-28 16:31 UTC, GamerBene19 commented on src/pages/admin/dishes.tsx
> +    { fieldName: 'aliases', displayName: 'Aliases' },
Since that column could contain multiple values - does it make sense to declare it `nonSortable`?

2022-07-28 18:06 UTC, stormofice commented on src/pages/admin/dishes.tsx
> +      },
Done.

2022-07-28 18:06 UTC, stormofice commented on src/pages/admin/dishes.tsx
> +        value: dish.aliases.at(0) ?? '<NULL>',
I thought it would behave differently if the array was empty, but this was not the case.
Fixed.

2022-07-28 18:06 UTC, stormofice commented on src/pages/admin/dishes.tsx
> +              {dish.aliases.map((x) => (
Done.

2022-07-28 18:06 UTC, stormofice commented on src/pages/admin/dishes.tsx
> +          dish.aliases.length == 1 ? (
Done.

2022-07-28 18:07 UTC, stormofice commented on src/pages/admin/dishes.tsx
> +    { fieldName: 'aliases', displayName: 'Aliases' },
Yes, I was not aware of this option.
Done.

2022-07-28 18:07 UTC, stormofice commented on src/pages/admin/dishes.module.scss
> +.main {
Done.

2022-07-28 18:07 UTC, stormofice commented on src/components/admin/DishInput.tsx
> +const DishInput = ({
Done.

2022-07-28 18:50 UTC, GamerBene19 requested changes
Changes look good. 

Two more things: I'd be nice if you could merge 
`fix: Rename dishes page` into `refactor(Dishes page): Move to own subdirectory` and the second thing is commented below

2022-07-28 18:50 UTC, GamerBene19 commented on src/components/admin/DishInput.tsx
> +const DishInput = ({
I was not talking about the name of the type but the name of the component. Sorry for the confusion.

2022-07-28 18:53 UTC, GamerBene19 commented on src/assets/icons/logout.svg
> +</svg>
It is.

2022-07-28 18:55 UTC, stormofice commented on src/components/admin/DishInput.tsx
> +const DishInput = ({
Fixed.

2022-07-28 19:00 UTC, GamerBene19 requested changes
Thanks!

One more thing: You seem to have forgotten one of my previous review comments

2022-07-28 19:00 UTC, GamerBene19 commented on src/pages/admin/dishes/index.tsx
> +                  {dish.aliases.map((x) => (
https://github.com/mensatt/frontend/pull/117#discussion_r932451142

2022-07-28 19:00 UTC, GamerBene19 commented on src/pages/admin/dishes.tsx
> +              {dish.aliases.map((x) => (
@stormofice Not done. See review below.

2022-07-28 19:04 UTC, GamerBene19 reviewed
Looking good now. As discussed I'd like to merge #122 into #119 first before merging this PR. Approval will be granted once #119 (including changes from #122) is merged.

2022-08-17 15:29 UTC, GamerBene19 approved these changes

2022-08-17 15:32 UTC, merged