CSS Magic
mensatt/frontend-old pull request #119
Opened 2022-07-27 18:34 UTC by maanex

2022-07-28 08:09 UTC, GamerBene19 requested changes
I'm really liking the changes so far - looking very good!

There are a few things that I'd change/like to talk about. See comments below.

2022-07-28 08:09 UTC, GamerBene19 commented on src/components/navigation/Navigation.tsx
> +    const out = array
What does `out` stand for here?

2022-07-28 08:09 UTC, GamerBene19 commented on src/components/occurrence/review-modal/form/Form.tsx
> +  // TODO @bene bitte useState oder so draus machen
Do you mean `useMemo`?

2022-07-28 08:09 UTC, GamerBene19 commented on src/components/occurrence/review-modal/form/Form.tsx
> +        {/* TODO show a preview of the selected image file here, just add an <img> tag or something i can style if there is a file selected */}
Are those TODOs for me?

2022-07-28 08:09 UTC, GamerBene19 commented on src/components/occurrence/review-modal/form/Form.tsx
> +        {/* TODO can we change the text here to something like "send review"? */}
Yes we can. We simply need another translation for this button.

2022-07-28 08:09 UTC, GamerBene19 commented on src/components/footer/Footer.tsx
> +      <div className={styles.logo} />
Maybe I'm misunderstanding, but isn't this div empty? What's its purpose?

2022-07-28 08:09 UTC, GamerBene19 commented on src/components/navigation/profile-button/ProfileButton.tsx
> +              // TODO bene mach mal login button hin
Tracked in #120

2022-07-28 08:09 UTC, GamerBene19 commented on src/pages/_app.tsx
> +        {/* https://stackoverflow.com/questions/44679794/position-fixed-on-chrome-mobile-causing-element-to-move-on-scroll-up-down */}
You might want to reference the answer you used (not just the question) here.

2022-07-28 08:09 UTC, GamerBene19 commented on src/styles/globals.scss
> +  background: linear-gradient(180deg, #dce3eb, #ebe6dc);
Is  that color still temporary? If not I think we can/should remove the comment above.

2022-07-28 08:09 UTC, GamerBene19 commented on src/components/occurrence/review-modal/form/Form.tsx
> +        <span>Click or drop an image to upload.</span>
Currently the only indication that a image was/is selected is the fact that the disclaimer is displayed. I think we should change `Click or drop an image to upload` text here if a user has selected pictures(/files).
![image](https://user-images.githubusercontent.com/20821976/181454425-a0a544ab-58f4-4a06-a84d-3cd6000a78cb.png)

2022-07-28 11:17 UTC, maanex commented on src/components/occurrence/review-modal/form/Form.tsx
> +  // TODO @bene bitte useState oder so draus machen
"useState oder so" = useMemo, ja 👍

2022-07-28 11:17 UTC, maanex commented on src/components/occurrence/review-modal/form/Form.tsx
> +        {/* TODO show a preview of the selected image file here, just add an <img> tag or something i can style if there is a file selected */}
Yes

2022-07-28 11:18 UTC, maanex commented on src/components/footer/Footer.tsx
> +      <div className={styles.logo} />
This div displays the logo. See CSS

2022-07-28 11:19 UTC, maanex commented on src/styles/globals.scss
> +  background: linear-gradient(180deg, #dce3eb, #ebe6dc);
All colors are temporary until we finalized the mensatt branding but feel free to remove the comment regardless.

2022-07-28 11:21 UTC, maanex commented on src/components/occurrence/review-modal/form/Form.tsx
> +        <span>Click or drop an image to upload.</span>
No we don't change the text. As I stated right below in line 159 (which you conveniently did not comment on lol) I would like to display a preview of the selected file there instead of the text all together.

2022-07-28 11:21 UTC, maanex commented on src/pages/_app.tsx
> +        {/* https://stackoverflow.com/questions/44679794/position-fixed-on-chrome-mobile-causing-element-to-move-on-scroll-up-down */}
Puh, ja

2022-07-28 11:23 UTC, maanex commented on src/components/navigation/Navigation.tsx
> +    const out = array
Out as in "output of this function". Feel free to rename if a different name fits you better 👍

2022-07-28 11:27 UTC, stormofice commented on src/components/occurrence/review-modal/form/Form.tsx
> +        <span>Click or drop an image to upload.</span>
How much work would be required to display a preview?
Does it fit in the scope of the PR or should it be tracked in a separate issue?

2022-07-28 12:05 UTC, GamerBene19 commented on src/components/occurrence/review-modal/form/Form.tsx
> +        <span>Click or drop an image to upload.</span>
An image preview is out of scope imo, but we should definitely change the text/contents of the rectangle once files are submitted.

2022-07-28 18:38 UTC, GamerBene19 commented on src/components/occurrence/review-modal/form/Form.tsx
> +        {/* TODO can we change the text here to something like "send review"? */}
Resolved in #122

2022-07-28 18:38 UTC, GamerBene19 commented on src/components/occurrence/review-modal/form/Form.tsx
> +        {/* TODO show a preview of the selected image file here, just add an <img> tag or something i can style if there is a file selected */}
Resolved in #122

2022-07-28 18:38 UTC, GamerBene19 commented on src/components/occurrence/review-modal/form/Form.tsx
> +  // TODO @bene bitte useState oder so draus machen
Resolved in #122

2022-07-28 18:39 UTC, GamerBene19 commented on src/components/navigation/Navigation.tsx
> +    const out = array
Not the greatest naming, but good enough to not change (for now).

2022-07-28 18:40 UTC, GamerBene19 commented on src/styles/globals.scss
> +  background: linear-gradient(180deg, #dce3eb, #ebe6dc);
Fair point. Leaving in.

2022-07-28 18:40 UTC, GamerBene19 commented on src/components/occurrence/review-modal/form/Form.tsx
> +        <span>Click or drop an image to upload.</span>
Resolved in #122 and tracked in #121

2022-07-28 18:42 UTC, GamerBene19 commented on src/pages/_app.tsx
> +        {/* https://stackoverflow.com/questions/44679794/position-fixed-on-chrome-mobile-causing-element-to-move-on-scroll-up-down */}
@maanex Can you confirm that it was [this](https://stackoverflow.com/a/51322362) answer? If yes I'll quickly change that comment and update the branch.

2022-07-28 21:29 UTC, maanex commented on src/pages/_app.tsx
> +        {/* https://stackoverflow.com/questions/44679794/position-fixed-on-chrome-mobile-causing-element-to-move-on-scroll-up-down */}
I can, will, and do confirm hereby that this (https colon slash slash stackoverflow dot com slash a slash 51322362) was in fact the one and only correct answer that influenced and dictated my code.
Kind Regards,
@maanex

2022-07-28 21:32 UTC, maanex commented on src/components/occurrence/review-modal/form/Form.tsx
> +        <span>Click or drop an image to upload.</span>
> An image preview is out of scope imo
It should not be, an image preview is essential to any image uploading form in 2022

2022-07-29 06:31 UTC, GamerBene19 commented on src/pages/_app.tsx
> +        {/* https://stackoverflow.com/questions/44679794/position-fixed-on-chrome-mobile-causing-element-to-move-on-scroll-up-down */}
Done

2022-07-29 06:32 UTC, GamerBene19 commented on src/components/occurrence/review-modal/form/Form.tsx
> +        <span>Click or drop an image to upload.</span>
> > An image preview is out of scope imo
> 
> It should not be, an image preview is essential to any image uploading form in 2022

Yes it is, but it's out of scope for this PR. It's one of the next tasks though for sure!

2022-07-29 07:26 UTC, GamerBene19 approved these changes
Lgtm now!

2022-07-29 07:26 UTC, merged