Address styling issues
mensatt/frontend-old pull request #146
Opened 2022-10-17 18:39 UTC by maanex

See #128

2022-10-17 21:52 UTC, GamerBene19 requested changes
See comments below

2022-10-17 21:52 UTC, GamerBene19 commented on src/components/occurrence/Occurrence.tsx
> +
useMemo pls

2022-10-17 21:52 UTC, GamerBene19 commented on src/components/occurrence/rating/OccurrenceRating.tsx
> +            }
Wieso das onClick nur, wenns nicht interactive is?

2022-10-17 21:53 UTC, GamerBene19 commented
@maanex Have you also looked at #52?

2022-10-18 07:28 UTC, maanex commented
> @maanex Have you also looked at #52?

All low priority, we can keep the branch though to do those kinds of improvements over time

2022-10-18 07:29 UTC, maanex commented on src/components/occurrence/Occurrence.tsx
> +
Warum? Ich den check nur in eine Variable gepackt, der war davor auch schon ohne memo vorhanden 🤔

2022-10-18 07:30 UTC, maanex commented on src/components/occurrence/rating/OccurrenceRating.tsx
> +            }
Weil wenn es active ist wird der Sterne Wert geschrieben, weitere Aktionen sollten da nicht ausgeführt werden.

2022-10-18 20:26 UTC, GamerBene19 approved these changes

2022-10-18 20:27 UTC, merged