feat: Introduce small constraints for username/comment
mensatt/frontend-old pull request #155
Opened 2022-10-19 21:52 UTC by stormofice

This prevents someone from submitting an empty username / comment and trims whitespaces off the start and end.

2022-10-20 09:52 UTC, GamerBene19 requested changes
Changes look good, however I did notice some things (see comment and this message)

1. Error warnings are not displayed after changing a field (notice how both warnings are only shown after I enter something into the nickname field)
2. Warnings don't go away once the fields are cleared again. I think this is important because we should not create the impression that you _have to_ enter a comment/username

https://user-images.githubusercontent.com/20821976/196917151-415120a6-af87-4fb7-9044-c534b35f117b.mp4

2022-10-20 09:52 UTC, GamerBene19 commented on src/components/occurrence/review-modal/form/Form.tsx
> +          comment: formState.comment ? formState.comment.trim() : '',
Shouldn't the else case here be `null`?

2022-10-20 09:55 UTC, maanex commented
![image](https://user-images.githubusercontent.com/23345879/196917605-9d6a3831-ba7c-435f-81b6-e4264e35ed2e.png)
How does this make sense? An optional field must not be empty?

2022-10-20 09:59 UTC, GamerBene19 commented
> ![image](https://user-images.githubusercontent.com/23345879/196917605-9d6a3831-ba7c-435f-81b6-e4264e35ed2e.png) How does this make sense? An optional field must not be empty?

The idea was to avoid cases like this where there are unnecessary whitespaces.
![image](https://user-images.githubusercontent.com/20821976/196918059-9e0f4ede-aeb1-4ef2-b0fe-cb881019b9c2.png)
Leading and trailing whitespaces can simply be trimmed, but we should make sure that if a user enters a comment/username (which he does not have to) it should not contain only whitespaces (since that would be pointless)

2022-10-20 10:05 UTC, maanex commented
Imo this should not result in an error at all. Your currently proposed flow is not very user friendly. Instead if the trimmed username results in an empty string just treat it as if no username was entered to begin with. A space as username = no nickname

2022-10-20 10:10 UTC, GamerBene19 commented
Sorry, didn't mean to close the PR

2022-10-20 10:11 UTC, GamerBene19 commented
> Imo this should not result in an error at all. Your currently proposed flow is not very user friendly. Instead if the trimmed username results in an empty string just treat it as if no username was entered to begin with. A space as username = no nickname

Yeah,  thinking about it - this might be the better approach :thinking:

2022-10-20 11:49 UTC, StealWonders commented on public/locales/en/common.json
> +  "noAuthorName": "(anon)",
anonymous

2022-10-20 11:59 UTC, StealWonders requested changes

2022-10-20 11:59 UTC, StealWonders commented on public/locales/de/common.json
> +  "reviewModalInvalidUsernameError": "Dein Username darf nicht leer sein",
Username -> Nutzername

2022-10-20 12:05 UTC, StealWonders approved these changes

2022-10-21 07:22 UTC, GamerBene19 requested changes

2022-10-21 07:22 UTC, GamerBene19 commented on src/components/occurrence/review-modal/form/Form.tsx
> +
Those assignments seem wrong. You should use setState - what's the reason for not using it?

2022-10-25 19:42 UTC, GamerBene19 commented on src/components/occurrence/review-modal/form/Form.tsx
> +
I think a good(ish) solution is to use useEffect and add a submitted property to the form state like so:
```
  const [formState, setFormState] = useState<
    AddReviewMutationVariables & { submitted: boolean }
  >({
    author: '',
    stars: 0,
    comment: null,
    images: null,
    occId: occurrenceId,
    submitted: false,
  });

  const formIsInvalid = useMemo(
    () => showMissingStarValueError || showWrongExtensionError,
    [showMissingStarValueError, showWrongExtensionError],
  );

  useEffect(() => {
    if (addReviewData) onSuccessfulSubmit();
  }, [addReviewData, onSuccessfulSubmit]);

  // Add review once it was submitted
  useEffect(() => {
    if (!formIsInvalid && formState.submitted)
      addReview({ variables: formState });
  }, [addReview, formIsInvalid, formState]);

  const handleSubmit = useCallback(
    (event: FormEvent) => {
      event.preventDefault();
      if (!formIsInvalid)
        setFormState({
          ...formState,
          author: formState.author.trim(),
          comment:
            formState.comment?.trim().length === 0
              ? null
              : formState.comment?.trim(),
          submitted: true,
        });
    },
    [formIsInvalid, formState],
  );
```

@stormofice also see 2nd question [above](https://github.com/mensatt/frontend/pull/155#discussion_r1000403196)

2022-10-25 19:46 UTC, stormofice commented on src/components/occurrence/review-modal/form/Form.tsx
> +          comment: formState.comment ? formState.comment.trim() : '',
Else case on the comment was fixed.

Author name does not need a ternary, as we author names are non nullable.
No author is indicated by '' not null, so trim is enough (as it will transform '       ' -> '').

2022-10-25 19:50 UTC, stormofice commented on src/components/occurrence/review-modal/form/Form.tsx
> +
Should be fixed.

2022-10-25 19:55 UTC, GamerBene19 approved these changes
LGTM :+1:

2022-10-25 19:55 UTC, GamerBene19 commented on src/components/occurrence/review-modal/form/Form.tsx
> +
it is

2022-10-25 19:58 UTC, GamerBene19 commented on src/components/occurrence/review-modal/form/Form.tsx
> +          comment: formState.comment ? formState.comment.trim() : '',
> as we author names are non nullable.

> No author is indicated by '' not null,

Why is that? Is that a backend thing? Shouldn't both just be nullable strings?

2022-10-25 20:12 UTC, stormofice commented on src/components/occurrence/review-modal/form/Form.tsx
> +          comment: formState.comment ? formState.comment.trim() : '',
Fixed in newest commit.

2022-10-25 20:15 UTC, GamerBene19 requested changes
Code looks good, only sth small to change

2022-10-25 20:15 UTC, GamerBene19 commented on src/components/occurrence/review-modal/form/Form.tsx
> +    console.log(formState);
Pls remove

2022-10-25 20:16 UTC, GamerBene19 commented on src/components/occurrence/review-modal/form/Form.tsx
> +          comment: formState.comment ? formState.comment.trim() : '',
:+1:

2022-10-25 20:16 UTC, stormofice commented on src/components/occurrence/review-modal/form/Form.tsx
> +    console.log(formState);
Oops!

2022-10-25 20:17 UTC, GamerBene19 commented
@stormofice Do you mind checking real quick if the author was wrong in the admin-panel also?

2022-10-25 20:21 UTC, stormofice commented
```typescript
[...]
return filteredReviews.map((elem) => ({
      dishName: elem.occurrence.dish.nameDe,
      author: elem.displayName || t('noAuthorName'),
      comment: elem.text || '<NULL>',
[...]
```
Seems fine?

2022-10-25 20:22 UTC, GamerBene19 commented
> ```ts
> [...]
> return filteredReviews.map((elem) => ({
>       dishName: elem.occurrence.dish.nameDe,
>       author: elem.displayName || t('noAuthorName'),
>       comment: elem.text || '<NULL>',
> [...]
> ```
> 
> Seems fine?

If that is the only occurrence in the admin-panel then yes - thanks for checking

2022-10-25 20:23 UTC, stormofice commented
It is done every time author is accessed.

2022-10-25 20:25 UTC, GamerBene19 approved these changes
LGTM (again)

2022-10-25 20:28 UTC, merged