Localisation
mensatt/frontend-old pull request #21
Opened 2022-05-20 13:34 UTC by maanex

2022-05-20 13:35 UTC, maanex commented
Do not merge yet, this PR was opened early to get the deploy preview.

2022-05-20 15:50 UTC, GamerBene19 requested changes
Siehe Kommentare, sonst siehts gut aus

2022-05-20 15:50 UTC, GamerBene19 commented on src/components/navigation/Navigation.tsx
> +      </div>
Eigene Komponete dafür?

2022-05-20 15:50 UTC, GamerBene19 commented on src/components/navigation/language-switcher/index.tsx
> +      </div>
Hier könnte man auch eine eigene Komponente draus machen

2022-05-20 15:50 UTC, GamerBene19 commented on src/components/navigation/mensa-selection/MensaSelection.module.scss
> -  border-radius: $header-element-br;
Ich nehme an das is irgendwo anders hingewandert?

2022-05-20 15:50 UTC, GamerBene19 commented on src/components/util/Icon.tsx
> +};
Der Kommentar sollte noch weg und vielleicht hier einfach 
```
const Icon = ({ name }: Props) => <div className="icon">{icons[name]}</div>;
```
?

2022-05-21 08:50 UTC, maanex commented on src/components/navigation/Navigation.tsx
> +      </div>
Kann man machen, aber ich finde man sollte nicht für alles ne neue Komponente machen sonst verliert man irgendwann komplett den überblick oder nich?

2022-05-21 08:50 UTC, maanex commented on src/components/navigation/language-switcher/index.tsx
> +      </div>
Oder man lässts einfach weil man das nur hier braucht und sonst nirgends

2022-05-21 08:51 UTC, maanex commented on src/components/navigation/mensa-selection/MensaSelection.module.scss
> -  border-radius: $header-element-br;
Korrekt!

2022-05-21 08:51 UTC, maanex commented on src/components/util/Icon.tsx
> +};
Oh ja der Kommentar ist Tech Debt, hau ihn raus 👍

2022-05-21 08:56 UTC, GamerBene19 commented on src/components/navigation/Navigation.tsx
> +      </div>
Jap, war mir auch nicht sicher, deswegen die Frage.

2022-05-21 08:56 UTC, GamerBene19 commented on src/components/util/Icon.tsx
> +};
Done.

2022-05-21 08:56 UTC, GamerBene19 commented on src/components/navigation/language-switcher/index.tsx
> +      </div>
Jap, war mir auch nicht sicher, deswegen der Konjunktiv.

2022-05-21 09:00 UTC, GamerBene19 approved these changes

2022-05-21 10:07 UTC, merged