Improve navigation
mensatt/frontend-old pull request #44
Opened 2022-05-24 12:22 UTC by maanex

2022-05-24 21:16 UTC, GamerBene19 requested changes

2022-05-24 21:16 UTC, GamerBene19 commented on src/components/navigation/Navigation.tsx
> +  language: boolean;
Jeweils `show...` ? Is ja ein boolean

2022-05-24 21:16 UTC, GamerBene19 commented on src/components/navigation/Navigation.tsx
> +    .flat()
`flatMap(...).flat(...)` macht wenig Sinn, oder?

2022-05-24 21:16 UTC, GamerBene19 commented on src/components/navigation/Navigation.tsx
> +  ].filter((i) => !!i) as JSX.Element[];
Das funktioniert zwar, ich finde aber 
```TS
const settingsItems = [];
if (opts.mensa) settingsItems.push(<MensaSelection />);
if (opts.language) settingsItems.push(<LanguageSwitcher />);
```
verständlicher/besser lesbar.

2022-05-24 21:16 UTC, GamerBene19 commented on src/components/navigation/Navigation.tsx
> +      {opts.brand ? <h1>Mensatt</h1> : ''}
Hier einfach `opts.brand ?? <h1>Mensatt</h1>`?

2022-05-24 21:16 UTC, GamerBene19 commented on src/components/navigation/back-button/index.tsx
> +        <p>{t('back')}</p>
Du verwendest hier die `back` translation, hast sie aber nicht hinzugefügt, oder?

2022-05-24 21:16 UTC, GamerBene19 commented on src/components/navigation/back-button/index.tsx
> +const BackButton = () => {
Vielleicht einen Parameter link o.a., damit man angeben kann, wohin man zurück will? Dann kann man die Komponente auch besser woanders einsetzen.

2022-05-24 21:16 UTC, GamerBene19 commented on src/components/navigation/Navigation.tsx
> +export type NavigaitonDisplayOptions = {
Das soll vermutlich `Navigation` heißen, und nicht `Navigaiton` nehm ich an

2022-05-24 21:16 UTC, GamerBene19 commented on src/pages/_app.tsx
> +};
Kannst du vielleich in ein zwei Sätzen erklären wie die Popups funktionieren?

2022-05-24 21:16 UTC, GamerBene19 commented on src/pages/_app.tsx
> +function MyApp({ Component, pageProps, router }: AppProps) {
Wieso fügst du hier `router` als prop hinzu statt ihn dir per `useRouter` hook zu holen?

2022-05-24 21:16 UTC, GamerBene19 commented on src/pages/_app.tsx
> +      .replace(/^\/|\/$/g, '') || 'index';
Wieso "muss" man den Path hier normalizen?

2022-05-24 21:16 UTC, GamerBene19 commented on src/components/navigation/Navigation.tsx
> +        {opts.action === 'back-button' ? <BackButton /> : ''}
Wenn du einen Back-Button einfügst kannst/solltest du auch den Back-Link in der page selbst löschen
![image](https://user-images.githubusercontent.com/20821976/170128287-9ecae49c-ee49-441f-ac9c-8e45f2dda513.png)

2022-05-24 21:16 UTC, GamerBene19 commented on src/components/navigation/Navigation.tsx
> +    .slice(0, -1);
Gibt scheinbar einee CSS-Option dafür: https://jsfiddle.net/kpq5h69c/. Falls du das wusstest und das aber Absicht war ignorier den Kommentar einfach.

2022-05-26 15:06 UTC, GamerBene19 commented on src/pages/_app.tsx
> +};
Nvmd, das hat ja garnichts mit den Popups zu tun. Das is einfach nur die menu-config abhängig von der Seite auf der man is...

2022-05-27 13:20 UTC, maanex commented on src/components/navigation/back-button/index.tsx
> +        <p>{t('back')}</p>
ja, out of scope für den pr :trollface:

2022-05-27 13:24 UTC, maanex commented on src/pages/_app.tsx
> +function MyApp({ Component, pageProps, router }: AppProps) {
Ich hab nicht viel Ahnung von NextJS, aber war das erste was ich auf Google gefunden hab und es funktioniert. Kannst du gerne umbauen wenn du willst 👍

2022-05-27 13:27 UTC, maanex commented on src/pages/_app.tsx
> +      .replace(/^\/|\/$/g, '') || 'index';
Lower Case: weil man sonst mensatt.de/PRIVACY aufrufen könnte und plötzlich seine Mensa auswählt
Erstes Replace: mmmmmm, präferenz lol
Zweites Replace: Tailing und Leading slashes entfernen weil sonst mensatt.de/privacy/ komisch wird 👍 
|| index: weil sonst die index Seite ein leerer String wäre

2022-05-27 13:27 UTC, maanex commented on src/components/navigation/Navigation.tsx
> +        {opts.action === 'back-button' ? <BackButton /> : ''}
**kannst** 😎

2022-05-27 13:27 UTC, maanex commented on src/components/navigation/Navigation.tsx
> +        {opts.action === 'back-button' ? <BackButton /> : ''}
jk wird gemacht

2022-05-27 13:29 UTC, maanex commented on src/components/navigation/Navigation.tsx
> +    .slice(0, -1);
Wusste ich, war Absicht das als einzelnes Element zu machen weil tldr. CSS ist poggers aber keine magie

2022-05-31 11:00 UTC, GamerBene19 commented on src/components/navigation/back-button/index.tsx
> +        <p>{t('back')}</p>
Ja kann/werde ich dann noch machen.

2022-05-31 11:01 UTC, GamerBene19 commented on src/pages/_app.tsx
> +      .replace(/^\/|\/$/g, '') || 'index';
:+1:

2022-05-31 11:50 UTC, GamerBene19 requested changes
Noch paar Kleinigkeiten, sonst schauts gut aus.

2022-05-31 11:50 UTC, GamerBene19 commented on src/components/navigation/Navigation.tsx
> +        )}
Wieso nicht einfach ein `showBackButton` statt der "action"?

2022-05-31 11:50 UTC, GamerBene19 commented on src/pages/_app.tsx
> +function MyApp({ Component, pageProps, router }: AppProps) {
Passe ich dann auch noch an, sobald du fertig bist.

2022-05-31 11:50 UTC, GamerBene19 commented on src/pages/_app.tsx
> +  const navOpts = layout.nav;
Beim ersten mal vergessen. Sowas sollte man wsl. memoizen mit dem useMemo-Hook

2022-05-31 11:50 UTC, GamerBene19 commented on src/components/navigation/Navigation.tsx
> +  actionData?: string;
Siehe Kommentar weiter unten in dieser Datei.

2022-05-31 11:52 UTC, GamerBene19 commented on src/components/navigation/Navigation.tsx
> +    .slice(0, -1);
Ah okay. Dann nvmd.

2022-05-31 11:58 UTC, maanex commented on src/components/navigation/Navigation.tsx
> +        )}
Weil man nicht gleichzeitig Wochentag Auswahl und Back Button haben können soll. Links soll der Übersichtlichkeit einen Zweck haben und nicht mehr. Alles was man individuell an und aus machen kann, kommt rechts hin 👍

2022-05-31 11:59 UTC, GamerBene19 commented on src/components/navigation/Navigation.tsx
> +        )}
Wäre es dann nicht besser direkt die Komponente zu übergeben, die links oben hin soll?

2022-05-31 12:03 UTC, maanex commented on src/components/navigation/Navigation.tsx
> +        )}
Puh wär ne Option, da hab ich nicht dran gedacht, sowas gibts im Vue land nicht... Kann man schon machen da bin ich offen für alles. So hats momentan halt den "Vorteil", dass man nur Komponenten da hin packen kann die auch wirklich da hin gehören. Aber wie gesagt hab da eigentlich keine Präferenz.

2022-05-31 12:22 UTC, GamerBene19 commented on src/components/navigation/back-button/index.tsx
> +        <p>{t('back')}</p>
Done.

2022-05-31 12:22 UTC, GamerBene19 commented on src/pages/_app.tsx
> +function MyApp({ Component, pageProps, router }: AppProps) {
Done.

2022-05-31 12:22 UTC, GamerBene19 commented on src/components/navigation/Navigation.tsx
> +        )}
Hab ich so umgesetzt.

2022-05-31 12:22 UTC, GamerBene19 commented on src/pages/_app.tsx
> +  const navOpts = layout.nav;
Done.

2022-05-31 12:23 UTC, GamerBene19 commented on src/components/navigation/Navigation.tsx
> +  actionData?: string;
Done.

2022-05-31 12:25 UTC, merged