Draft: Comments
mensatt/frontend-old pull request #64
Opened 2022-06-06 21:45 UTC by GamerBene19

This branch is not ready for merging yet. Do **NOT** merge without a prior review and approval. 

This branch provides support for showing comments as fetched by the API.

2022-06-06 22:15 UTC, stormofice requested changes
Changes look good to me, however I would rephrase the german `noCommentMsg`.

2022-06-06 22:15 UTC, stormofice commented on public/locales/de/common.json
> +  "noCommentMsg": "Erzähl doch mal, wie's geschmeckt hat!",
```suggestion
  "noCommentMsg": "Erzähl doch mal, wie es dir geschmeckt hat!",
```

2022-06-07 07:44 UTC, GamerBene19 reviewed
Weil das "mein" PR is kann ich keine changes requesten, deswegen der comment nur.
Sie das als "changes requested" an @herkulessi. Du könntest auch, wenn du die changes gemacht und gepushed hast, nen neuen PR von **dir** erstellen. Dann kann man da auch vernünftig reviewen.

2022-06-07 07:44 UTC, GamerBene19 commented on public/locales/de/common.json
> +  "noCommentMsg": "Erzähl doch mal, wie's geschmeckt hat!",
+1

2022-06-07 07:44 UTC, GamerBene19 commented on src/components/dish/Dish.tsx
> +  };
Hier würde ich den type aus der query picken. Das is zukunftssicherer.

2022-06-07 07:44 UTC, GamerBene19 commented on src/components/dish/Dish.tsx
> +  }
1. Kein let (sondern nur const) verwenden. Mit let kann ich etwas machen wie 
    ```TS
    let stringOrNumber;
    if (randomCondition) {
        stringOrNumber = '0';
    } else {
        stringOrNumber = 1;
    }
    ```
    und das ist sehr unschön (v.a. in der Zukunft). U.a. weil das dann vom Typ `any` ist. Mit const geht das nicht.
2. useMemo hook verwenden. Damit wird das nur geupdated wird, wenn sich was ändert.

Ich würde hier sowas machen: 
```TS
import { useMemo } from 'react';
...
const comments = useMemo(() => {
    if (dish.reviews.length < 1) return t('noCommentMsg');
    return dish.reviews.map((review) => (
      <DishComment
        key={review.id}
        author={review.displayName}
        text={review.text}
      />
    ));
  }, [dish.reviews, t]);
```

2022-06-07 09:24 UTC, maanex commented on src/components/dish/Dish.tsx
> +  };
Warum `Array<{...}>` und nicht `{...}[]`?

2022-06-07 09:26 UTC, GamerBene19 commented on src/components/dish/Dish.tsx
> +  };
Nehme an der Type is direkt aus den autogenreated gql-types.

2022-06-07 09:56 UTC, GamerBene19 commented
Ah noch eine Sache @herkulessi, den `Stub, schould not get pushed.` commit noch entfernen bitte.

Soft reset auf den commit vor dem stub commit (müsste der aktuelle von master sein) und dann einen neuen commit erstellen, der beide Änderungen enthält. Wenn du zufrieden bist musst du dann force pushen.

2022-06-07 09:59 UTC, herkulessi commented
Mach ich nacher, bin gerade nicht zuhause

2022-06-07 12:32 UTC, tobiges commented
Should be named Review instead of Comment. The stars information should also be displayed with the review.

2022-07-16 16:26 UTC, maanex commented
This pr is stale, any status updates? Is anyone still working on this or is this outdated?

2022-07-22 11:57 UTC, stormofice commented
Reviews will be implemented in #97.

2022-07-22 11:57 UTC, closed without merging