Footer styling
mensatt/frontend-old pull request #89
Opened 2022-06-16 15:17 UTC by maanex

ye

2022-06-16 15:25 UTC, GamerBene19 requested changes
Man kann auf der Seite jetzt "nach oben scrollen" (siehe Bild), das ging vorhin nicht.

![image](https://user-images.githubusercontent.com/20821976/174104927-7d657221-1185-4fc4-b902-207940a6aba9.png)

2022-06-16 15:25 UTC, GamerBene19 commented on src/components/navigation/profile-button/ProfileButton.tsx
> +const ProfileButton = () => {
Das eigentliche Problem (das der Button im logged-out-Fall empty is) wird durch den rename nicht gelöst.
![image](https://user-images.githubusercontent.com/20821976/174104592-c5800aa5-9475-4a5e-867f-303434a5e349.png)

Was is da der Plan?

2022-06-16 15:27 UTC, maanex commented on src/components/navigation/profile-button/ProfileButton.tsx
> +const ProfileButton = () => {
Der plan ist dass du das component so umbaust dass da ein login button steht wenn man nicht eingeloggt ist. Und nicht einfach kein button da ist, wie momentan.

2022-06-16 15:28 UTC, maanex commented
> Man kann auf der Seite jetzt "nach oben scrollen" (siehe Bild), das ging vorhin nicht.

Can't reproduce, won't fix

2022-06-18 17:15 UTC, GamerBene19 commented on src/components/navigation/profile-button/ProfileButton.tsx
> +const ProfileButton = () => {
I see. Dann mach ich das dannach noch :+1:

2022-06-18 17:15 UTC, GamerBene19 commented
> Man kann auf der Seite jetzt "nach oben scrollen" (siehe Bild), das ging vorhin nicht.
> 
> ![image](https://user-images.githubusercontent.com/20821976/174104927-7d657221-1185-4fc4-b902-207940a6aba9.png)

Nvmd. Lag an einem meiner addons.

2022-06-18 17:16 UTC, GamerBene19 approved these changes

2022-06-18 17:16 UTC, merged