:rocket: Add Reviews :rocket:
mensatt/frontend-old pull request #97
Opened 2022-07-21 08:48 UTC by GamerBene19

2022-07-23 23:49 UTC, stormofice requested changes
Hi, thanks for the great contribution 😄

I am really pleased with the progress so far, but got some general questions regarding the changes and small nitpicks.

2022-07-23 23:49 UTC, stormofice commented on public/locales/de/common.json
> +  "reviewModalNameLabel": "Dein Nickname",
```suggestion
  "noAuthorName": "(kein name)",
  "rate": "Bewerten",
  "reviewModalHeading": "Wie war '{{name}}'?",
  "reviewModalNameLabel": "Dein Name",
```
I'm not sure about using 'nickname' in this context, it seems a bit dated.
A generic 'name' or 'username' might suffice?

2022-07-23 23:49 UTC, stormofice commented on public/locales/de/common.json
> +  "noImagesMsg": "Es gibt noch keine Bilder für dieses Gericht...",
Using these ellipses (…) here feels a little off-putting, but I don't know if we should replace them.
(This also applies to the english version, but I do not want to split the discussion)

2022-07-23 23:49 UTC, stormofice commented on public/locales/en/common.json
> +  "reviewModalNameLabel": "Your Nickname",
```suggestion
  "noAuthorName": "(no name)",
  "rate": "Rate",
  "reviewModalHeading": "How was '{{name}}'?",
  "reviewModalNameLabel": "Your Name",
```
I feel like 'name' feels more natural in english than in german.

2022-07-23 23:49 UTC, stormofice commented on src/components/occurrence/Occurrence.tsx
> +        : 'https://api.mensatt.de/v1/graphql',
I feel like the backend url should be in a separate config file (or any another solution to manage configurations in a single place). However, I don't know if this is feasible or best practice in React/Frontend, so I'm also fine keeping it as is.

2022-07-23 23:49 UTC, stormofice commented on src/components/occurrence/Occurrence.tsx
> +  );
I believe that [GQL supports filters](https://www.apollographql.com/blog/graphql/filtering/how-to-search-and-filter-results-with-graphql/) (requires backend support), should we consider using them instead?
Does filtering the results frontend-side cause unnecessary data usage?

2022-07-23 23:49 UTC, stormofice commented on src/components/occurrence/Occurrence.tsx
> +            // height={600}
```suggestion
```
Seems to be a leftover?

2022-07-23 23:49 UTC, stormofice commented on src/components/occurrence/Occurrence.tsx
> +                  even replace popups with own implementation
I think we should create our own implementation in the (post-release) future, as we had several issues with reactjs-popup already.

2022-07-23 23:49 UTC, stormofice commented on src/components/occurrence/review-modal/ReviewModal.tsx
> +const MAX_UPLOAD_FILE_SIZE = 20 * 1024 * 1024;
Similar thoughts as above, could we centralize these kinds of configurations?

2022-07-23 23:49 UTC, stormofice commented on src/components/occurrence/review-modal/ReviewModal.tsx
> +  occurrenceID,
```suggestion
  occurrenceId,
```
I don't have a problem with fully capitalizing abbreviations shorter than two characters, but I can't help and notice that you used `reviewId` in line 99 below. I believe we should keep it consistent.

2022-07-24 08:15 UTC, GamerBene19 commented on public/locales/de/common.json
> +  "reviewModalNameLabel": "Dein Nickname",
I agree with your conclusion that `Nickname` is dated.

I didn't want to use `username` as (at least for me) that implies that you can log into something and have an account - which a) you currently can't
b) you won't necessarily need in the future 

I haven't used `Name` because (at least for me) that implies that you need to enter your actual name - which definitely should not be the case here.

I'm happy for other suggestions ^^

2022-07-24 08:16 UTC, GamerBene19 commented on public/locales/de/common.json
> +  "noImagesMsg": "Es gibt noch keine Bilder für dieses Gericht...",
Agreed. I think we should either get rid of them completely or leave one dot.
Any opinions?

2022-07-24 08:19 UTC, GamerBene19 commented on src/components/occurrence/Occurrence.tsx
> +  );
> I believe that [GQL supports filters](https://www.apollographql.com/blog/graphql/filtering/how-to-search-and-filter-results-with-graphql/) (requires backend support), should we consider using them instead?

Definitely, but as you said backend support for that is currently not present. 

> Does filtering the results frontend-side cause unnecessary data usage?

In this case yes (but minor), as we first get all reviews from the backend to then filter out all the unwanted ones.

2022-07-24 08:22 UTC, GamerBene19 commented on src/components/occurrence/Occurrence.tsx
> +            // height={600}
It is, but it's related to styling so I've left it in for now. @maanex Can this be deleted?

2022-07-24 08:25 UTC, GamerBene19 commented on src/components/occurrence/Occurrence.tsx
> +                  even replace popups with own implementation
Agreed, but obv should be done post-release as you mentioned. Can you create an issue for it?

2022-07-24 08:28 UTC, GamerBene19 commented on src/components/occurrence/review-modal/ReviewModal.tsx
> +const MAX_UPLOAD_FILE_SIZE = 20 * 1024 * 1024;
I will answer above and mark this convo as resolved.

2022-07-24 08:30 UTC, GamerBene19 commented on src/components/occurrence/Occurrence.tsx
> +        : 'https://api.mensatt.de/v1/graphql',
Yeah, we should introduce some kind of config. But should be it's own issue imo - could you create it (and ideally add a checklist of places where such "config values" are currently present)?

2022-07-24 08:40 UTC, GamerBene19 commented on src/components/occurrence/review-modal/ReviewModal.tsx
> +  occurrenceID,
Good point. I'll unify the names to `fooId`

2022-07-24 08:58 UTC, GamerBene19 commented on src/components/occurrence/review-modal/ReviewModal.tsx
> +  occurrenceID,
Done.

2022-07-24 09:47 UTC, GamerBene19 commented on public/locales/en/common.json
> +  "reviewModalNameLabel": "Your Nickname",
See concerns [above](https://github.com/mensatt/frontend/pull/97#discussion_r928217613)

2022-07-24 12:28 UTC, maanex commented on public/locales/de/common.json
> +  "noImagesMsg": "Es gibt noch keine Bilder für dieses Gericht...",
One dot sounds good to me.

2022-07-24 12:32 UTC, maanex commented on src/components/occurrence/Occurrence.tsx
> +            // height={600}
The react <Image> element can automatically request different source images from the server depending on it's rendered display size. This does not work well with css resizing but that's a different topic. For now I think this can be removed but we should keep track of image optimization in general - perhaps in a new issue?

2022-07-24 13:52 UTC, stormofice commented on src/components/occurrence/Occurrence.tsx
> +                  even replace popups with own implementation
Tracked in #104.

2022-07-24 13:54 UTC, stormofice commented on src/components/occurrence/Occurrence.tsx
> +            // height={600}
Tracked in #105.

2022-07-24 13:59 UTC, stormofice commented on src/components/occurrence/Occurrence.tsx
> +  );
Tracked in [mensatt-backend/#82.](https://github.com/mensatt/backend/issues/82)

2022-07-24 14:02 UTC, stormofice commented on public/locales/de/common.json
> +  "reviewModalNameLabel": "Dein Nickname",
(Resolved mirror discussion for english names)

Discord/sigfood uses nickname, so I guess we can keep it.

2022-07-24 14:09 UTC, GamerBene19 commented on public/locales/de/common.json
> +  "noImagesMsg": "Es gibt noch keine Bilder für dieses Gericht...",
One dot it will be then :+1:

2022-07-24 14:11 UTC, GamerBene19 commented on public/locales/de/common.json
> +  "noImagesMsg": "Es gibt noch keine Bilder für dieses Gericht...",
Done.

2022-07-24 14:43 UTC, stormofice commented on src/components/occurrence/Occurrence.tsx
> +        : 'https://api.mensatt.de/v1/graphql',
Tracked in #106.

2022-07-24 14:43 UTC, stormofice submitted a review, later dismissed
Looks good to me, approved!

2022-07-26 12:58 UTC, GamerBene19 commented
Is/Will be implemented in seperate PRs

2022-07-26 12:58 UTC, closed without merging